"""added Book, LibraryBook, and the associations between the different models

Revision ID: 2966816edfc7
Revises: 1ad267c1c325
Create Date: 2025-03-18 13:03:04.796774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2966816edfc7'
down_revision = '1ad267c1c325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('author', sa.String(length=50), nullable=False),
    sa.Column('genre', sa.String(length=50), nullable=True),
    sa.Column('published_year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('library_books',
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_library_books_book_id_books')),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], name=op.f('fk_library_books_library_id_libraries')),
    sa.PrimaryKeyConstraint('library_id', 'book_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('library_books')
    op.drop_table('books')
    # ### end Alembic commands ###
